AppVerk\UserBundle\Entity\Role:
    type: mappedSuperclass
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            name: name
        credentials:
            type: array
            name: credentials
            nullable: true
            length: 65535
        deletable:
            type: boolean
            nullable: true
